name = "jadwalin"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "jadwalin"
database_id = "01571a43-18dd-42b5-a54f-d4297f45f877"