name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  WORKDIR: ./
  NODE_VERSION: 20
  VERSION_SCRIPT: node -p "require('./package.json').version"

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      
      - name: Get Version
        id: package
        run: |
          VERSION=$(${{ env.VERSION_SCRIPT }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
    
      - name: Install & Build
        run: |
          yarn install
          yarn build

      - name: Compress Build
        run: tar -czf build.tar.gz node_modules .next

      - name: Upload Build
        uses: appleboy/scp-action@master
        with:
          source: ${{ env.WORKDIR }}/build.tar.gz
          target: ${{ secrets.APP_DIR }}
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
      
      - name: Deply Build & Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }}/${{ env.WORKDIR }}
            rm -rf node_modules .next
            tar -xzf build.tar.gz
            git pull --all
            bash -ic "yarn prisma generate && pm2 restart ecosystem.config.js"

      - name: Notify Telegram, Success
        if: ${{ failure() == false }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ✅ Deploy jadwalin ${{ steps.package.outputs.version }} Success
      
      - name: Notify Telegram, Failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 🔥 Deploy jadwalin ${{ steps.package.outputs.version }} Failed